/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'other' : null } |
  { 'entertainment' : null } |
  { 'travel' : null } |
  { 'rent' : null } |
  { 'utilities' : null } |
  { 'groceries' : null } |
  { 'schoolFees' : null };
export interface Expense {
  'id' : bigint,
  'date' : string,
  'description' : string,
  'category' : Category,
  'amount' : bigint,
  'paidBy' : string,
  'splitAmong' : Array<string>,
}
export interface Member { 'balance' : bigint, 'name' : string }
export interface MonthlySummary {
  'totalSpending' : bigint,
  'categoryBreakdown' : Array<[Category, bigint]>,
}
export interface Settlement {
  'to' : string,
  'from' : string,
  'note' : [] | [string],
  'timestamp' : Time,
  'amount' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExpense' : ActorMethod<
    [string, bigint, Category, string, Array<string>, string],
    undefined
  >,
  'addMember' : ActorMethod<[string], undefined>,
  'addSettlement' : ActorMethod<
    [string, string, bigint, [] | [string]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'getBalances' : ActorMethod<[], Array<Member>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpense' : ActorMethod<[bigint], [] | [Expense]>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getMembers' : ActorMethod<[], Array<Member>>,
  'getMonthlySummary' : ActorMethod<[string], MonthlySummary>,
  'getSettlements' : ActorMethod<[], Array<Settlement>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeMember' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];